# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'prova.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_GestorePiscina(object):
    def setupUi(self, GestorePiscina):
        GestorePiscina.setObjectName("GestorePiscina")
        GestorePiscina.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(GestorePiscina)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(40, 70, 93, 28))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(60, 110, 93, 28))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(80, 150, 93, 28))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(110, 190, 93, 28))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(130, 230, 93, 28))
        self.pushButton_5.setObjectName("pushButton_5")
        GestorePiscina.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(GestorePiscina)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        self.menuhome = QtWidgets.QMenu(self.menubar)
        self.menuhome.setObjectName("menuhome")
        GestorePiscina.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(GestorePiscina)
        self.statusbar.setObjectName("statusbar")
        GestorePiscina.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuhome.menuAction())

        self.retranslateUi(GestorePiscina)
        QtCore.QMetaObject.connectSlotsByName(GestorePiscina)

    def retranslateUi(self, GestorePiscina):
        _translate = QtCore.QCoreApplication.translate
        GestorePiscina.setWindowTitle(_translate("GestorePiscina", "MainWindow"))
        self.pushButton.setText(_translate("GestorePiscina", "1"))
        self.pushButton_2.setText(_translate("GestorePiscina", "2"))
        self.pushButton_3.setText(_translate("GestorePiscina", "3"))
        self.pushButton_4.setText(_translate("GestorePiscina", "4"))
        self.pushButton_5.setText(_translate("GestorePiscina", "5"))
        self.menuhome.setTitle(_translate("GestorePiscina", "home"))
