from PyQt5.QtGui import QPixmap, QStandardItemModel, QStandardItem
from PyQt5.QtWidgets import QWidget, QGridLayout, QPushButton, QSizePolicy, QLabel, QMessageBox

from cliente.view.VistaCliente import VistaCliente
from listaclienti.views.VistaInserisciCliente import VistaInserisciCliente
from listaclienti.views.VistaListaClienti import VistaListaClienti
from listaclienti.controllore.ControlloreListaClienti import ControlloreListaClienti
from listadipendenti.views.VistaListaDipendenti import VistaListaDipendenti
from listaoggettipersi.views.VistaListaOggettiPersi import VistaListaOggettiPersi
from listaprenotazioni.views.VistaListaPrenotazioni import VistaListaPrenotazioni
from listaservizi.views.VistaListaServizi import VistaListaServizi
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Home(object):
    def setupUi(self, Home):
        Home.setObjectName("Home")
        Home.setEnabled(True)
        Home.resize(624, 411)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Home.sizePolicy().hasHeightForWidth())
        Home.setSizePolicy(sizePolicy)
        Home.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        Home.setStyleSheet("")

        self.controller = ControlloreListaClienti()

        self.centralwidget = QtWidgets.QWidget(Home)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setStyleSheet("font: 75 italic 10pt \"MS Sans Serif\";")
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.West)
        self.tabWidget.setIconSize(QtCore.QSize(30, 40))
        self.tabWidget.setObjectName("tabWidget")
        self.home = QtWidgets.QWidget()
        self.home.setObjectName("home")
        self.label_7 = QtWidgets.QLabel(self.home)
        self.label_7.setGeometry(QtCore.QRect(270, 10, 261, 81))
        self.label_7.setStyleSheet("font: 75 italic 20pt \"MS Sans Serif\";")
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.home)
        self.label_8.setGeometry(QtCore.QRect(220, 70, 341, 41))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.home)
        self.label_9.setGeometry(QtCore.QRect(270, 100, 341, 41))
        self.label_9.setObjectName("label_9")
        self.splitter_5 = QtWidgets.QSplitter(self.home)
        self.splitter_5.setGeometry(QtCore.QRect(0, 0, 211, 381))
        self.splitter_5.setStyleSheet("font: 75 italic 12pt \"MS Sans Serif\";")
        self.splitter_5.setOrientation(QtCore.Qt.Vertical)
        self.splitter_5.setObjectName("splitter_5")
        self.label = QtWidgets.QLabel(self.splitter_5)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.splitter_5)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.splitter_5)
        self.label_3.setObjectName("label_3")
        self.label_5 = QtWidgets.QLabel(self.splitter_5)
        self.label_5.setObjectName("label_5")
        self.label_4 = QtWidgets.QLabel(self.splitter_5)
        self.label_4.setObjectName("label_4")
        self.label_6 = QtWidgets.QLabel(self.splitter_5)
        self.label_6.setObjectName("label_6")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("GUI/immaginiprogetto/home (1).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon.addPixmap(QtGui.QPixmap("GUI/immaginiprogetto/home.png"), QtGui.QIcon.Active, QtGui.QIcon.On)
        self.tabWidget.addTab(self.home, icon, "")
        self.clienti = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.clienti.sizePolicy().hasHeightForWidth())
        self.clienti.setSizePolicy(sizePolicy)
        self.clienti.setFocusPolicy(QtCore.Qt.TabFocus)
        self.clienti.setToolTip("")
        self.clienti.setWhatsThis("")
        self.clienti.setObjectName("clienti")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.clienti)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.listaClienti = QtWidgets.QListView(self.clienti)
        self.listaClienti.setObjectName("listaClienti")
        self.horizontalLayout.addWidget(self.listaClienti)
        VistaListaClienti.update_ui_clienti(self)

        self.splitter = QtWidgets.QSplitter(self.clienti)
        self.splitter.setMinimumSize(QtCore.QSize(231, 0))
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.visualizzaCliente = QtWidgets.QPushButton(self.splitter)
        self.visualizzaCliente.setMinimumSize(QtCore.QSize(231, 0))
        self.visualizzaCliente.setMaximumSize(QtCore.QSize(16777215, 243))
        self.visualizzaCliente.setStyleSheet("font: 75 italic 8pt \"MS Sans Serif\";")
        self.visualizzaCliente.setObjectName("visualizzaCliente")


        self.inserisciNuovoCliente = QtWidgets.QPushButton(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.inserisciNuovoCliente.sizePolicy().hasHeightForWidth())
        self.inserisciNuovoCliente.setSizePolicy(sizePolicy)
        self.inserisciNuovoCliente.setMinimumSize(QtCore.QSize(231, 0))
        self.inserisciNuovoCliente.setStyleSheet("font: 75 italic 8pt \"MS Sans Serif\";")
        self.inserisciNuovoCliente.setObjectName("inserisciNuovoCliente")
        self.horizontalLayout.addWidget(self.splitter, 0, QtCore.Qt.AlignVCenter)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("GUI/immaginiprogetto/customer giusto.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon1.addPixmap(QtGui.QPixmap("GUI/immaginiprogetto/customer giusto(1).png"), QtGui.QIcon.Active, QtGui.QIcon.On)
        self.tabWidget.addTab(self.clienti, icon1, "")
        self.prenotazioni = QtWidgets.QWidget()
        self.prenotazioni.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.prenotazioni.setObjectName("prenotazioni")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.prenotazioni)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.listaPrenotazioni = QtWidgets.QListView(self.prenotazioni)
        self.listaPrenotazioni.setObjectName("listaPrenotazioni")
        self.horizontalLayout_2.addWidget(self.listaPrenotazioni)
        self.splitter_2 = QtWidgets.QSplitter(self.prenotazioni)
        self.splitter_2.setOrientation(QtCore.Qt.Vertical)
        self.splitter_2.setObjectName("splitter_2")
        self.visualizzaPrenotazione = QtWidgets.QPushButton(self.splitter_2)
        self.visualizzaPrenotazione.setStyleSheet("font: 75 italic 8pt \"MS Sans Serif\";")
        self.visualizzaPrenotazione.setObjectName("visualizzaPrenotazione")
        self.inserisciNuovaPrenotazione = QtWidgets.QPushButton(self.splitter_2)
        self.inserisciNuovaPrenotazione.setStyleSheet("font: 75 italic 8pt \"MS Sans Serif\";")
        self.inserisciNuovaPrenotazione.setObjectName("inserisciNuovaPrenotazione")
        self.horizontalLayout_2.addWidget(self.splitter_2, 0, QtCore.Qt.AlignVCenter)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("GUI/immaginiprogetto/booking.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon2.addPixmap(QtGui.QPixmap("GUI/immaginiprogetto/booking (1).png"), QtGui.QIcon.Active, QtGui.QIcon.On)
        self.tabWidget.addTab(self.prenotazioni, icon2, "")
        self.oggetti = QtWidgets.QWidget()
        self.oggetti.setObjectName("oggetti")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.oggetti)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.listaOggetti = QtWidgets.QListView(self.oggetti)
        self.listaOggetti.setObjectName("listaOggetti")
        self.horizontalLayout_3.addWidget(self.listaOggetti)
        self.splitter_3 = QtWidgets.QSplitter(self.oggetti)
        self.splitter_3.setMinimumSize(QtCore.QSize(231, 0))
        self.splitter_3.setOrientation(QtCore.Qt.Vertical)
        self.splitter_3.setObjectName("splitter_3")
        self.visualizzaOgetto = QtWidgets.QPushButton(self.splitter_3)
        self.visualizzaOgetto.setStyleSheet("font: 75 italic 8pt \"MS Sans Serif\";")
        self.visualizzaOgetto.setObjectName("visualizzaOgetto")
        self.inserisciNuovoOggetto = QtWidgets.QPushButton(self.splitter_3)
        self.inserisciNuovoOggetto.setStyleSheet("font: 75 italic 8pt \"MS Sans Serif\";")
        self.inserisciNuovoOggetto.setObjectName("inserisciNuovoOggetto")
        self.horizontalLayout_3.addWidget(self.splitter_3, 0, QtCore.Qt.AlignVCenter)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("GUI/immaginiprogetto/lost-items.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon3.addPixmap(QtGui.QPixmap("GUI/immaginiprogetto/lost-items (1).png"), QtGui.QIcon.Active, QtGui.QIcon.On)
        self.tabWidget.addTab(self.oggetti, icon3, "")
        self.servizi = QtWidgets.QWidget()
        self.servizi.setObjectName("servizi")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.servizi)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.listaServizi = QtWidgets.QListView(self.servizi)
        self.listaServizi.setObjectName("listaServizi")
        self.horizontalLayout_4.addWidget(self.listaServizi)
        self.visualizzaServizio = QtWidgets.QPushButton(self.servizi)
        self.visualizzaServizio.setMinimumSize(QtCore.QSize(231, 0))
        self.visualizzaServizio.setStyleSheet("font: 75 italic 8pt \"MS Sans Serif\";")
        self.visualizzaServizio.setObjectName("visualizzaServizio")
        self.horizontalLayout_4.addWidget(self.visualizzaServizio)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("GUI/immaginiprogetto/walk.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon4.addPixmap(QtGui.QPixmap("GUI/immaginiprogetto/walk (1).png"), QtGui.QIcon.Active, QtGui.QIcon.On)
        self.tabWidget.addTab(self.servizi, icon4, "")
        self.dipendenti = QtWidgets.QWidget()
        self.dipendenti.setObjectName("dipendenti")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.dipendenti)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.listaDipendenti = QtWidgets.QListView(self.dipendenti)
        self.listaDipendenti.setObjectName("listaDipendenti")
        self.horizontalLayout_5.addWidget(self.listaDipendenti)
        self.splitter_4 = QtWidgets.QSplitter(self.dipendenti)
        self.splitter_4.setMinimumSize(QtCore.QSize(231, 0))
        self.splitter_4.setOrientation(QtCore.Qt.Vertical)
        self.splitter_4.setObjectName("splitter_4")
        self.pushButton_2 = QtWidgets.QPushButton(self.splitter_4)
        self.pushButton_2.setStyleSheet("font: 75 italic 8pt \"MS Sans Serif\";")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.splitter_4)
        self.pushButton_3.setStyleSheet("font: 75 italic 8pt \"MS Sans Serif\";")
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_5.addWidget(self.splitter_4, 0, QtCore.Qt.AlignVCenter)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("GUI/immaginiprogetto/lifeguard.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon5.addPixmap(QtGui.QPixmap("GUI/immaginiprogetto/lifeguard (1).png"), QtGui.QIcon.Active, QtGui.QIcon.On)
        self.tabWidget.addTab(self.dipendenti, icon5, "")
        self.verticalLayout.addWidget(self.tabWidget)
        Home.setCentralWidget(self.centralwidget)

        self.retranslateUi(Home)
        self.tabWidget.setCurrentIndex(0)
        self.visualizzaCliente.clicked.connect(self.show_selected_info_clienti)
        self.inserisciNuovoCliente.clicked.connect(self.show_new_cliente)
        QtCore.QMetaObject.connectSlotsByName(Home)

    def retranslateUi(self, Home):
        _translate = QtCore.QCoreApplication.translate
        Home.setWindowTitle(_translate("Home", "MainWindow"))
        self.label_7.setText(_translate("Home", "BENVENUTI!"))
        self.label_8.setText(_translate("Home", "QUESTO É IL PROGRAMMA DI GESTIONE"))
        self.label_9.setText(_translate("Home", "DELLA PISCINA COMUNALE"))
        self.label.setText(_translate("Home", "HOME"))
        self.label_2.setText(_translate("Home", "CLIENTI"))
        self.label_3.setText(_translate("Home", "PRENOTAZIONI"))
        self.label_5.setText(_translate("Home", "OGGETTI SMARRITI"))
        self.label_4.setText(_translate("Home", "SERVIZI"))
        self.label_6.setText(_translate("Home", "DIPENDENTI"))
        self.visualizzaCliente.setText(_translate("Home", "VISUALIZZA CLIENTE"))
        self.inserisciNuovoCliente.setText(_translate("Home", "INSERISCI NUOVO CLIENTE"))
        self.visualizzaPrenotazione.setText(_translate("Home", "VISUALIZZA PRENOTAZIONE"))
        self.inserisciNuovaPrenotazione.setText(_translate("Home", "INSERISCI NUOVA PRENOTAZIONE"))
        self.visualizzaOgetto.setText(_translate("Home", "VISUALIZZA OGGETTO"))
        self.inserisciNuovoOggetto.setText(_translate("Home", "INSERISCI NUOVO OGGETTO"))
        self.visualizzaServizio.setText(_translate("Home", "VISUALIZZA SERVIZIO"))
        self.pushButton_2.setText(_translate("Home", "VISUALIZZA DIPENDENTE"))
        self.pushButton_3.setText(_translate("Home", "INSERISCI NUOVO DIPENDENTE"))

    def show_selected_info_clienti(self):
        try:
            selected = self.listaClienti.selectedIndexes()[0].row()
            cliente_selezionato = self.controller.get_cliente_by_index(selected)
            self.vista_cliente = VistaCliente(cliente_selezionato, self.controller.rimuovi_cliente, VistaListaClienti.update_ui_clienti)
            self.vista_cliente.show()
        except:
            QMessageBox.critical(None,
                                 'Errore',
                                 'Nessun cliente selezionato.',
                                 QMessageBox.Ok,
                                 QMessageBox.Ok)

    def show_new_cliente(self):
        self.vista_inserisci_cliente = VistaInserisciCliente(self.controller, VistaListaClienti.update_ui_clienti)
        self.vista_inserisci_cliente.show()
